# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
if !defined? VAGRANTFILE_API_VERSION
  VAGRANTFILE_API_VERSION = "2"
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.shell = "/bin/ash"
  config.vm.synced_folder ".", "/vagrant", type: "rsync",
  rsync__args: ["--verbose", "--archive", "-z"]
  config.vm.provider "virtualbox" do |vb|
    vb.check_guest_additions = false
  end
end
